/**
 * Shared constants for member forms — used by both the admin MemberForm
 * and the portal MemberProfileEditForm.
 *
 * The districts list contains all 64 districts of Bangladesh (using the
 * official Bengali-standardized names: Chattogram, Cumilla, Barishal, Jashore).
 * The banks list contains all scheduled banks operating in Bangladesh
 * (state-owned, private commercial, foreign, and specialized banks).
 */

// All 64 districts of Bangladesh, alphabetically sorted.
// Source: Bangladesh Bureau of Statistics / Local Government Division.
export const BANGLADESH_DISTRICTS = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barishal",
  "Bhola",
  "Bogura",
  "Brahmanbaria",
  "Chandpur",
  "Chapainawabganj",
  "Chattogram",
  "Chuadanga",
  "Cumilla",
  "Cox's Bazar",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jamalpur",
  "Jashore",
  "Jhalokati",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachhari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrakona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
] as const

// All scheduled banks operating in Bangladesh.
// Includes state-owned, private commercial, foreign, and specialized banks.
// Source: Bangladesh Bank (central bank) official list of scheduled banks.
export const BANGLADESH_BANKS = [
  // --- State-owned commercial banks ---
  "Sonali Bank",
  "Janata Bank",
  "Agrani Bank",
  "Rupali Bank",
  "Bangladesh Development Bank",
  "BASIC Bank",
  // --- Specialized banks ---
  "Bangladesh Krishi Bank",
  "Rajshahi Krishi Unnayan Bank",
  "Probashi Kallyan Bank",
  "Karmasangsthan Bank",
  "Palli Sanchay Bank",
  "Ansar-VDP Unnayan Bank",
  "Jubilee Bank",
  // --- Private commercial banks ---
  "AB Bank",
  "City Bank",
  "National Bank",
  "United Commercial Bank",
  "Eastern Bank",
  "NCC Bank",
  "IFIC Bank",
  "Pubali Bank",
  "Dhaka Bank",
  "Prime Bank",
  "Southeast Bank",
  "Al-Arafah Islami Bank",
  "Social Islami Bank",
  "BRAC Bank",
  "One Bank",
  "Bank Asia",
  "Mutual Trust Bank",
  "Trust Bank",
  "Standard Bank",
  "Mercantile Bank",
  "Global Islami Bank",
  "Modhumoti Bank",
  "Shimanto Bank",
  "Shanta Bank",
  "Citizens Bank PLC",
  "Community Bank Bangladesh",
  "NRB Bank",
  "NRBC Bank",
  "Midland Bank",
  "SBAC Bank",
  // --- Foreign banks ---
  "Standard Chartered Bank",
  "HSBC",
  "Citibank N.A.",
  "State Bank of India",
  "Commercial Bank of Ceylon",
  "Habib Bank",
  "National Bank of Pakistan",
  "Bank Al-Falah",
  "Woori Bank",
  "ICBC",
  // --- Mobile banking / fintech (commonly used as bank alternatives) ---
  "bKash",
  "Nagad",
  "Rocket (DBBL)",
] as const
